example_site/content/blog/20180410 pagination.md
example_site/content/manual/Template format.md
example_site/templates/blog/index.html
example_site/templates/index.html
example_site/templates/sitemap.xml
example_site/templates/tests/bydate.html
publ/category.py
publ/entry.py
publ/queries.py
publ/rendering.py
publ/utils.py
publ/view.py

Implements #13 and also cleans up `categories.subcats`
Views with pagination restrictions (`limit`, `date`) now get `next` and `previous` properties
that refer to their neighboring views. Views also now have `link` which allows you to get a
link to the view in question.
Any templates that used `category.subcats_recursive` now need to be changed to `category.subcats(recurse=True)`.
Added pagination to the blog and tests index templates, manually tested out `?date=` URLs.

Implement view pagination and some other niceness

---

example_site/content/manual/Template format.md
example_site/static/style.css
example_site/templates/index.html
publ/queries.py
publ/view.py

Fixes issue #34 and also cleans up some other code
In addition to fixing the bug, this does the following:
* Adds some convenience properties, `view.newest` and `view.oldest`, which link to the newest and oldest entries in the view
* Fixes up some documentation 
* Cleans up some logic 
None
Browsed the tests and manual using date-based queries

Fix entry pagination

---

example_site/content/manual/Template format.md
example_site/templates/error.html
publ/__init__.py
publ/rendering.py
publ/utils.py

Fixes issue #5
If `app.debug` isn't true, we now register a `rendering.render_exception` method as the default error handler for all `Exception`s.
Tested locally with: `pipenv run python3 main.py`

Add production-mode exception handler

---

example_site/content/blog/20180411 entry IDs.md
example_site/content/manual/Entry file format.md
example_site/templates/blog/entry.html
example_site/templates/blog/index.html

Fixes issue #40. Turns out MathJax makes this really easy; it's dependent on the template providing the MathJax JavaScript include.

Enable math rendering via MathJax

---

Pipfile
Pipfile.lock
config.py.dist
example_site/content/blog/20180416 caching.md
example_site/templates/blog/index.html
example_site/templates/index.html
main.py
publ/__init__.py
publ/caching.py
publ/entry.py
publ/rendering.py

Enable caching for the most I/O-bound operations
This adds the use of [Flask-Cache](https://pythonhosted.org/Flask-Cache/) to add some very basic caching; in particular, we now cache:
* Template lookups
* Entry message loads/parses
* Renders of entry and category pages
There now needs to be a caching configuration added to `config.py`. See `config.py.dist` for some reasonable defaults.
* Ensure that different pages on category views look different
* If content changes, the view shouldn't change until the cache TTL expires

Implement basic caching

---

publ/queries.py
publ/utils.py

Fixes issue #48 by normalizing the time zone on the query range
So it turns out the "unnecessary" split for entry date vs. display date ended up being very useful, because that made fixing this bug very easy. Turns out SQLite doesn't do timezone-aware queries after all! So even though that work was done unnecessarily to fix an unrelated bug it still ended up being useful in the long run.
This should also 
Tested the blog view with `/blog/?date=2018-04-17` and ensured that pagination works correctly.

Fix the timezone for the query span

---

Makefile
publ/entry.py
publ/markdown.py
publ/utils.py
publ/view.py
setup.py

Adds `entry.archive` to the templates, and also changes `limit` parameters to `count`
Now you can get the "archive link" for an entry with e.g.
{{entry.archive(paging='day',template=template.name,category=category.path)}}
This also finally fixes `CallableProxy` to allow variable positional argument lists, and as such the above can also be written:
{{entry.archive('day',template.name,category.path)}}
The docs will be updated over on publ.beesbuzz.biz.
All templates that use a `limit` parameter (on a view or an entry text configuration) need to be changed to `count` instead.

Add entry archive links

---

publ/markdown.py

fixes #63 - Don't put an imageset `<div>` inside a `<p>`
Takes the ultra-cheesy option: assumes that images will be inside a `<p>` and just closes and reopens it outside of the `<div>`
now I hate myself
ran various entries through the validator

Fix image div nesting

---

publ/category.py
publ/entry.py

Fixes #51 
Turns out most of them were in `view.py` already; there were a couple in `entry.py` which were just dead code anyway, and there was one trivial one in `category.py`.

Remove the last few remaining spurious __getattr__s

---

publ/cards.py
publ/entry.py
publ/image.py
publ/markdown.py
publ/utils.py

Add the `entry.card` primitive for generating OpenGraph metadata, as a solution for #45 
Now we can make cards for Twitter et al. Yay.
Verified working with publ.beesbuzz.biz content

Add OpenGraph card support

---

Pipfile
publ/__init__.py
publ/async.py
publ/category.py
publ/image.py
publ/rendering.py

Render images in the background, and attempt to have the client fetch them asynchronously. Implements #53 
When images are being rendered they go into a background threadpool. Images that are being rendered asynchronously get returned with a special `_async` handler, which retries loading the image a few times (with a short backoff) and then returns a generated gradient image if it fails.
Unfortunately WSGI (and therefore Flask) is blocking and can't do proper async, so the hope is that the redirect causes the client to reorder its pending resource fetches.
At some point there should be a client-side JS library that detects the async/deferred images and attempts to reload them periodically. However, the gradient acts as an indicator that the user can refresh the page and maybe it'll work. …

Render images asynchronously

---

publ/category.py
publ/entry.py
publ/model.py
publ/queries.py
publ/view.py

Fixes #91 
Entries now have three (3) date fields! One for UTC time (used only for visibility determination), one for local time (used for pagination and sorting), and one for canonical entry time (used for display and `.humanize()`).
The UTC date is probably not necessary anymore, as peewee seems to support timezone-aware datetimes and we can probably just use that for the filter criterion.
None
Generated a bunch of random test entries with varying timezones and determined that sorting and pagination were working correctly. These will be at http://publ.beesbuzz.biz/tests/date-based when published.

Use local dates for pagination and sorting

---

publ/image.py
publ/rendering.py

Fixes #94
The Image object returned by `image()` now supports a `get_css_background()` method, which returns the complete CSS attributes needed to use the image as a background-image.

Add CSS background-image generator

---

publ/entry.py
publ/image.py
publ/markdown.py

Fixes #99
When rendering a title, run it through Markdown, but with all `<p>` tags removed. Also, adds an optional argument, `markup`, which will strip out all other tags when false.
As a bonus, `body` and `more` now get a parameter, `xhtml=True`, to render XHTML instead of plain HTML. This turns out to not be particularly useful, although maybe someone will need it in the future.
Also, as part of ongoing documentation cleanup efforts, `Entry`'s `CallableProxy` properties are now done as `@cached_property` getters.
Templates now need to specify `{{ entry.title(markup=False) }}` wherever a title can be used where markup isn't permitted (such as in `<title>` elements on HTML and Atom).
Thorough tests on the publ.beesbuzz.biz site files

Support Markdown in entry titles

---

publ/__init__.py
publ/category.py
publ/entry.py
publ/index.py
publ/markdown.py
publ/rendering.py
publ/view.py

Fixes #104 
A refactor of the way error pages work, which also makes NotFound errors get promoted to a 503 with an appropriate retry header if the site is currently being reindexed.
Hammered at reloading while reindexing beesbuzz.biz

Improve errors during reindexing

---

publ/__init__.py
publ/rendering.py

Fixes #90 
Adds a template function, `get_template()`, that can be used in conjunction with Jinja's `include` predicate.
Tests added to publ.beesbuzz.biz in the `tests/subtemplate` section.
Production-worthy usage on beesbuzz.biz.

Add the get_template() function for including sub-template fragments

---

publ/index.py
publ/rendering.py

Disable caching during site index; fixes #84 
Simply uses Flask-Caching's `unless` function. Easy.

Disable cache during index

---

publ/__init__.py
publ/path_alias.py
publ/rendering.py

This allows sites to declare their own path-alias regular expression rules that are evaluated after the built-in path-alias logic.
```
app = publ.publ(__name__, config)
import flask
@app.path_alias_regex(r'/d/([0-9]{8}(_w)?)\.php')
def redirect_date(match):
return flask.url_for('category', category='comics', date=match.group(1)), True
```
Tested on beesbuzz.biz

Path-Alias regex hook

---

publ/__init__.py
publ/config.py
publ/image.py
publ/maintenance.py

Fixes issue #102, and automatically cleans old image renditions from the rendition cache.
When an image rendition is used, the file timestamp gets touched, marking the rendition as recently-used.
A periodic maintenance process (default: once an hour) now scans the image rendition cache for renditions that haven't been used in a while (default: one week) and removes them.
Maintenance tasks are also now encapsulated in a recurring task scheduler, which presently only runs whenever a request occurs (rather than using a background thread).
Stale images no longer take up disk space indefinitely. On the plus side this saves space; on the minus side this means that images on infrequently-accessed content pages may become invalid for the purposes of image search or hotlinks or whatever.
manually …

Automatically purge image rendition cache

---

publ/entry.py

Semi-stable entry ID and UUID generation
Rather than leaving it to chance, UUID is generated based on the original file path, and entry ID is generated based on a pseudorandom sequence generated by taking the MD5 hash of the file path appended with an attempt number.
In theory this should always generate IDs and UUIDs the same on any deployment target, although entry ID will also be dependent on how many other entries there are. But this at least mitigates the problem with Heroku deployments causing a lot of spurious RSS entries.
Manual smoke testing :(

Change to generating UUID and entry-ID by hashing the file path

---

.gitignore
Pipfile
Pipfile.lock
publ/__init__.py
publ/category.py
publ/config.py
publ/entry.py
publ/image.py
publ/index.py
publ/markdown.py
publ/model.py
publ/path_alias.py
publ/queries.py
publ/rendering.py
publ/view.py
setup.py
tests/schemaTest.py

Replace peewee with Pony ORM; resolves #120 in a rather roundabout way
Pony ORM is better in many ways than peewee. So we use it now.
Different table name mappings means users will have to manually delete their databases. This also requires a config change.
Lots of hammering away and performance testing, mostly.

Replace peewee with Pony

---

publ/caching.py
publ/index.py
publ/rendering.py
publ/template.py

Implements ETag and Last-Modified for cache control; resolves issue #129 
For category and entry views, it generates a fingerprint and last-modified time of the most recent relevant file. The relevant files considered are:
* The view template
* The most recently-published entry (based on publish time, not file modification time)
* The most recently-indexed file
* The entry itself, if applicable
This is a pessimistic time stamp, the idea being that any modification to an entry might end up changing things like previous/next links or any sidebar showing recent changes or the like. This avoids having to do an expensive process of evaluating the template to see what related things have changed (which would defeat the entire purpose to this caching in the first place).
Using `feedparser` I …

Implement ETag and Last-Modified

---

publ/category.py
publ/entry.py
publ/markdown.py
publ/rendering.py
publ/utils.py

Implement entry resolution for internal entry links; fixes #142 
When a Markdown entry sees an internal link, it tries to resolve it as an entry first, using the search path for the template context (or the content directory if it starts with `/`). If this finds an entry, the link target is set to the entry's `link` attribute using the template's configuration.
For example, previously an entry link like
```markdown
[foo](123)
```
would just generate
```html
<a href="123">foo</a>
```
which would require at least a redirect to the entry from the path resolver, and also required external feed readers to be savvy enough to rewrite URLs (which is technically a violation of the Atom spec although most feed readers do the rewriting even though they're not supposed to). Now it will generate a …

Improve internal reference links

---

publ/category.py
publ/entry.py
publ/rendering.py
publ/template.py
publ/utils.py

It now works on Windows! Fixes #97 (finally)
The problems all turned out to be due to path separator stuff. Fixing everything required:
* use `os.path.samefile` for file path comparisons
* Normalize paths using `os.normpath` wherever Publ was touching file paths
* Denormalize everything back to using `/` wherever Flask was touching it, because Flask fixes that on its own
Also it turns out that Python 3 still defaults to ISO-8859-1 even in the year 2018, so all `file()` calls now have an explicit encoding set.
Tested Publ-site thoroughly on both Windows and macOS

Get Publ working natively on Windows

---

publ/entry.py
publ/html_entry.py
publ/image.py
publ/links.py
publ/markdown.py
publ/utils.py

Supports rewriting link and image targets in HTML entries; fixes #136 and #154.
This adds a simple HTML transform step which scans all elements for `href` and `src` links, and rewrites their targets appropriately. In the case of `<img>` tags it also uses the `width` and `height` attributes in addition to the template configuration to select the appropriate renditions.
Adds a lot of functionality to HTML entries, but also changes the Image API somewhat. See https://github.com/PlaidWeb/publ-site/commit/baaea3b6737a7ca816bfa0113d23908af2237d85 for related documentation changes.
Added tests in https://github.com/PlaidWeb/publ-site/commit/baaea3b6737a7ca816bfa0113d23908af2237d85

Support entry and image links in plain-HTML entries

---

publ/__init__.py
publ/entry.py
publ/html_entry.py
publ/image.py
publ/links.py
publ/markdown.py
publ/model.py
publ/rendering.py

Allows the use of assets that PIL doesn't support in both image and link contexts. Fixes #141.
If we try to resolve an image or a link to a file which isn't supported by PIL, the file gets indexed as an asset instead. If a file is indexed as an asset then it becomes retrievable via a URL like `_file/<shorthash>/<basename>`, which simply sends the file directly if it's been indexed as an asset.
This also ends up refactoring a lot of link handling stuff and makes for fewer weird paths things can go through. There are still a couple of places where `utils.remap_link_target` are called, but these can probably be refactored away in the future.
Added a bunch of tests to publ-site; see https://github.com/PlaidWeb/publ-site/commit/66b7a049be5b7f8d4898dc89f7ec2d7a14072980

Support linking to non-image asset files

---

publ/image.py

In re: #77 
Implements cropping for LocalImages. The cropping happens before resizing the rendition, so a cropped image can be subsequently rescaled.
This PR adds cropping functionality to LocalImages. A new argument to Markdown image inlines, `crop=(left,top,right,bottom)`, will be processed to this end. To handle cropping "before" resizing logic so that they can happen separately and synergize, I calculate the size of the crop box and use it for the input size in the resizing calculation function `LocalImage.get_rendition_size`. Resizing based off of the dimensions of the original image wouldn't work of course since cropping gives us a new image with new dimensions. In `LocalImage._render`, [PIL.Image.Image.crop](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Imag …

Add cropping for LocalImages

---

publ/category.py
publ/entry.py
publ/path_alias.py
tests/content/aliases.md

Fixes #166 
Instead of having to specify `Path-Unalias` to remove a path alias (which, incidentally, wasn't even being done on categories), Publ now just rebuilds all aliases when an entry or category file is scanned. 
It's a little inefficient (one extra database transaction per scanned file) but that's not that big a deal.
No more need for `Path-Unalias`
Made a test entry with two `Path-Alias` headers, looked for them in the database, removed one header, looked in the database.

Remove that Path-Unalias grodiness

---

publ/entry.py
publ/model.py
publ/queries.py
publ/rendering.py
publ/view.py
tests/content/tags/tag1.md
tests/content/tags/tag2.md
tests/content/tags/tag3.md
tests/content/tags/untagged.md
tests/templates/tags/entry.html
tests/templates/tags/index.html

Implements the tagging system; fixes #22 
Each tag is just a row in the `EntryTag` table that links a tag to an entry. The tags are normalized lowercase in the database.
Views now get a `tag=` parameter which can be a string or a list. The category endpoint also gets a `tag` parameter which filters the category to that tag. If multiple tags are specified, they are treated as a logical `OR`. In the future there may be a means of specifying an `AND` clause instead (for example, having separate `tag_any` and `tag_all` mechanisms), but that feels overly complicated for now.
See `tests/tags` in the testing site.

Implement tagging system

---

publ/view.py
tests/templates/tags/index.html

Remove all pagination filters from unpaginated views; fixes #175 in the simplest way possible
If there's no pagination on a view that has a start offset, ignore the offset, since it makes no sense to have any sort of pagination in that case anyway (since any previous/next page would include all the content from the current page).
See changes to the tag tests, which are what exposed the problem in the first place.

Remove filters from unpaginated views

---

publ/entry.py
publ/model.py
publ/path_alias.py
tests/content/redirections/draft.md
tests/content/redirections/gone.md

Respect the permissions of entries before following their Path-Alias; fixes #183
When consulting an entry-based Path-Alias, treat an invisible entry as if the alias didn't exist.
See `draft.md` and `gone.md` in `tests/content/redirections`

Honor permissions on Path-Alias

---

publ/category.py
tests/content/tags/subcat/subcat1.md
tests/content/tags/subcat/subcat2.md
tests/templates/tags/browse.html
tests/templates/tags/index.html

Fixes #182 
Rather than denormalize the category information on the tags, I realized that the category-based index would be enough. So this ended up being a lot easier than I thought.
I'm not terribly happy with the API being attached to `category` when it's really providing `view`-type functionality but that's what makes the most sense for the 99% case, anyway. If you really want to apply it at the view level you can do something like `category.root.tags(**view.spec)` although that's a bit ghastly.
Tests in the test site

Category tags

---

publ/entry.py
publ/rendering.py
tests/content/empty slug text.md

If an entry has empty slug text, don't put the `-` into the URL
updated localhost:5000/557; the trailing `-` is still allowed (mostly because fixing that would be tricky), but any generated permalinks or redirections should now go without.

Improve empty slug text

---

publ/entry.py
publ/html_entry.py
tests/content/html entities etc.html
tests/content/relative entry links.md

Fixes #198 
Previously there was no handling of comments, entities, or charrefs. Which was causing them to get eaten. Oops.
This also disables smartypants on plain HTML entries because
1. smartypants was adding an extra level of `\` processing for some reason
2. HTML entries are supposed to be minimally-processed anyway
tests added to repo

Fix support for HTML entities

---

Pipfile.lock
publ/links.py

Fixes #201 by forwarding the `absolute` argument along to the asset link resolver
When I rewrote how asset links resolve I neglected to notice that the new argument parsing stuff wasn't actually forwarding `absolute` along. Now it does.
`curl localhost:5000/feed?id=315` to verify asset links are being rewritten correctly.

Forward absolute parameter to asset link resolver

---

Pipfile.lock
publ/rendering.py
tests/content/err/failure.md
tests/templates/err/error.html
tests/templates/err/index.html

Show a default error page if no error template is provided; Fixes #135 
It's unclear where the default Flask error handler actually comes from or how to trigger it (`flask.abort()` simply throws an `HTTPException` which causes an exception loop) so instead we embed a simple template into Publ itself. This has the benefit of providing slightly more information anyway.
Used `./runTests.sh` to check the following URLs:
```
http://localhost:5000/asdf
http://localhost:5000/error
http://localhost:5000/err/
http://localhost:5000/2348242
http://localhost:5000/err/2348242
```
Used `pipenv run python3 ./tests.py` to run in prod and checked the same URLs. In particular, `/err/` should show the `templates/err/error.html` template in production but still show a stack trace in test.

Fix default error handler

---

publ/entry.py
publ/html_entry.py
publ/utils.py

Fixes #206 by not discarding entities and charrefs in default document transforms
Moved the entityref and charref handlers out of the HTMLEntry parser and into the base HTMLTransform class.
see `tests/content/apostrophe titles.md`

Fix discarded entities and charrefs

---

publ/links.py
tests/content/aliases.md

Fixes #212 
Path-aliases remain unresolved. Now the resolver will absoluteify unresolved links too.
Modified test id 674 (`aliases.md`), and tested correct result with:
curl localhost:5000/feed?id=674

Properly absolute-ify unresolved HREFs

---

publ/rendering.py

Fixes #208
Adds the headers necessary to request disabling search and archive caching.
Tested hidden entry 339 to make sure the headers are present, and public entry 308 to make sure they aren't.

Disable caching/indexing for HIDDEN entries

---

publ/view.py
tests/templates/feed.xml
tests/templates/index.html

Add `current` and `is_current` properties to the view; fixes #210 
Now it's easier to tell if a view has an offset, and allows quickly consulting a current version of the view.
Added respective functionality to `templates/index.html` and `templates/feed.xml`, and verified its correctness with e.g.
http://localhost:5000/feed?tag=asdf
http://localhost:5000/feed?tag=asdf&date=2017
http://localhost:5000/&date=2019

Add View.current and View.is_current

---

publ/cards.py
publ/category.py
publ/entry.py
publ/rendering.py
publ/utils.py
tests/content/cards/html badly-formed.html
tests/content/cards/html entry with summary.html
tests/content/cards/html well-formed.html
tests/content/cards/html with image.html
tests/content/cards/markdown entry with summary.md
tests/content/cards/markdown with image.md
tests/content/cards/markdown with paragraph.md
tests/templates/cards/entry.txt
tests/templates/style.css

Fixes #219
This refactoring makes it a lot easier to follow the code flow for the various properties-that-are-also-functions in the various API classes, except for where the internal function is used from multiple call sites.
In doing this refactoring I also noticed some issues with entry.summary and entry.card; they would have both failed if parameters were passed to them on entries with a `Summary:` field, and HTML entries were being completely ignored. Now there is a very basic HTML card parser and cards/summaries go through the improved CallableProxy pattern.

Refactor CallableProxy call sites

---

Makefile
Pipfile.lock
publ/__init__.py
publ/config.py
publ/entry.py
publ/model.py
publ/rendering.py
publ/user.py
publ/utils.py
publ/view.py
tests.py
tests/content/auth/admins.md
tests/content/auth/allow everyone.md
tests/content/auth/allow logged-out.md
tests/content/auth/friends and specific.md
tests/content/auth/friends but not good_friends.md
tests/content/auth/friends except friend2.md
tests/content/auth/friends.md
tests/content/auth/no_auth.md
tests/templates/_entry.html
tests/templates/auth/index.html
tests/templates/feed.xml
tests/templates/index.html
tests/users.cfg

Closes #147 - allows for a basic Authl configuration and uses it to allow fine-grained private access to entries.
Entries for which the user isn't authorized won't appear in views, except with minimal data in the `view.unauthorized` list. Direct access to an entry redirects to the login page (currently just the minimal Authl stub page; see issue #233 for an improved login flow).
Created new test suite in `/auth/`

Implement private content

---

publ/rendering.py
tests/templates/auth/unauthorized.html

If a user is logged in and doesn't have access, provide a better signaling mechanism. Fixes #247 
If a user is logged in and doesn't have access to an entry, Publ will render a 403 page using the `unauthorized` template (falling back to the usual 403 handler) so that they get an appropriate message regarding why they can't access the page.

Improve the unauthorized flow for logged-in users

---

publ/__init__.py
publ/utils.py
tests/templates/auth/index.html
tests/templates/auth/unauthorized.html

Add `login` and `logout` template objects. Fixes #246 
Templates now get `login` and `logout` which provide an easy way to produce correct auth-related links. They can be called with or without parameters; if given a parameter it will be used as the redirection path, and additional parameters can be sent to the handler itself, e.g. `me` for specifying a username to log in as.
Updated the various auth-related templates and hammered away at this for a bit.

Add login and logout helpers

---

publ/markdown.py

Fixes #226 
Turns out feedvalidator barfs on malformed `style` attributes.
Looked at image rendition tests; before there were a lot of `<div class="foo" style>`, after it's just `<div class="foo">`.

Remove spurious image set attributes

---

publ/caching.py
publ/category.py
publ/entry.py
publ/user.py
publ/utils.py
publ/view.py
tests/content/auth/friends and specific.md

Fixes #255 and also cleans up the way cache keys are generated in general
The main problem behind issue 255 was that the `@caching.memoize` decorator appears to NOT md5sum the function name as part of the cache key, which was causing the `user.groups` property (and *only* that) to fail memoization on memcached. The direct fix for that was to refactor the way that `User.groups` was put together, by putting that functionality into `user.get_groups`, which also no longer returns the total group->user mapping (which wasn't very useful anyway).
As part of my investigations into this I realized that there's an easier/cleaner way to generate cache keys anyway.
Configured tests.py to use the memcached backend and ensured that the error spew went away, indicating that the data is actually being …

Refactor cache key generation

---

publ/__init__.py
publ/config.py
publ/user.py
tests.py

Prune auth log entries periodically. Fixes #259 
Adds a periodic maintenance task which will purge auth log entries. Default is to keep the last month of auth log entries, checked once an hour.
Set purge interval to 30 seconds and max age to 90 seconds, observed that things worked correctly

Prune the auth log

---

Pipfile.lock
publ/__init__.py
publ/utils.py
tests.py
tests/templates/login.html

Forces all login stuff to happen over https.
Even if `AUTH_FORCE_SSL` was enabled, only the actual login would take place over https; the cookie would not be set https-only and the login page would also be in cleartext. Due to how session cookies work this means that it's possible for a user's session to be hijacked via packet sniffing, as well as a myriad small privacy violations.
If `AUTH_FORCE_HTTPS` or `AUTH_FORCE_SSL` is set, the login and logout link builders force https, and the cookie is set https-only.
This also renames `AUTH_FORCE_SSL` to the more pedantically-correct `AUTH_FORCE_HTTPS` and deprecates the former with a warning.
non-force case: tested on localhost tests
force-https: deployed WIP version to beesbuzz.biz

If auth requires https, only allow the login page and cookie to be https too

---

publ/rendering.py
pylintrc
runTests.sh
tests/content/err/_.cat
tests/content/err/failure.md
tests/content/redirections/redirect filename.md
tests/content/redirections/redirect image.md
tests/templates/auth/unauthorized.html
tests/templates/tags/index.html

Simplify some of the routing rules and the way that entry URLs get canonicized
Instead of comparing the slug_text and category, just compare the URL with the expected URL. This will help with #286 down the road but it mostly just cleans up some code now. It also finally removes the ambiguity around empty slugs, as to whether the URL should end with a `-` or not.
Also fixed a bunch of tests which have been broken for a while.
Did the usual litany of redirection tests, on both authorized and unauthorized entries, including test entry 557 (empty slug).

Improve URL routing and canonicization

---

Pipfile.lock
publ/__init__.py
publ/rendering.py
publ/utils.py
setup.py
tests/templates/auth/unauthorized.html
tests/templates/err/403.html
tests/templates/login.html

Treat the need to log in as a 401 error; Closes #294 
By treating the page as a 401 error, we are able to eventually add in a `WWW-Authenticate:` header to support AutoAuth flows.
Usual battery of manual auth tests

Treat not-logged-in as a 401 error instead of redirecting

---

publ/rendering.py
publ/user.py
publ/utils.py
tests/templates/_entry.html

Stashes the active user on the request stash
Previously we were re-creating the user object from the session every time the user object was needed; future user verification may be a multi-step networked process which would make this incredibly inefficient.
For this change it also adds a utility decorator to memoize results to the stash, which might be useful somewhere else down the road.
Verified that the `get_active` function is only being  called once per page request

Actually stash the user record into the request globals

---

publ/rendering.py
publ/tokens.py
publ/user.py
tests/templates/login.html
tests/templates/userinfo.html

Support the `Authorized:` header with a token type of `Bearer`; closes #295 
If there's an `Authorized` header on the request, attempt to parse and verify it to get the user information. If it succeeds, treat that pageview as having authorization. Otherwise, throw an appropriate error about the failed parse even if the request is for a public resource.
[Relevant error case discussion](https://chat.indieweb.org/dev/2019-10-29#t1572387697863700)
This change also introduces the concept of authentication provenance for the user, as well as user scope.
Added `/userinfo.html` on tests to check the current user authorization mode.
Used https://gimme-a-token.5eb.nl/ to test the success and failure cases for Bearer authorization; example commands:
```
curl http://localhost:5000/userinfo -H …
```

Implement Authorized: header support

---

publ/__init__.py
publ/entry.py
publ/tokens.py
publ/utils.py
publ/view.py
tests/content/auth/upgrade/private 0.md
tests/content/auth/upgrade/private 1.md
tests/content/auth/upgrade/private 2.md
tests/content/auth/upgrade/private 3.md
tests/content/auth/upgrade/public 1.md
tests/content/auth/upgrade/public 2.md
tests/content/auth/upgrade/public 3.md

Add the appropriate `WWW-Authenticate` headers when there's hidden content that could be visible; closes #293; closes #292 
On a page where a change in authentication might cause an increase in visibility, a `WWW-Authenticate` and `Link` header get added.
The logic for when they get added is:
* on any `401 Unauthorized` response  (including those caused by a bad/invalid token)
* on any page where an attempt is made to access an unauthorized entry, but only if there is no active user
Both logged-in and logged-out, looked at the response headers on the `/auth/` view, the `/auth/upgrade/` individual entries, and on `/auth/562-admin-only`.

Add authentication headers for restricted content

---

publ/rendering.py
publ/utils.py

Upgrade 401 Unauthorized login pages to https if https. Fixes #303 
Not much more to say.
Ran locally with `AUTH_FORCE_HTTPS`, a redirect on a private entry happened. Turned that option off, the redirect stopped happening.

Upgrade 401 login pages to https if so configured

---

publ/cards.py
publ/image/__init__.py
publ/image/image.py
publ/markdown.py
tests/content/images/limits.md

If an image in a gallery is being skipped due to `count` or `count_offset`, still render the fullsize image and add it to the gallery set. Closes #308 
In a context where there's a `gallery_id` and a `link`, this does *not* generate the fullsize renditions, as there would be no point to that anyway.
see test 1864

Show all images in a gallery, even if skipped

---

publ/entry.py
publ/markdown.py
tests/content/footnotes.md

Improve footnote references for `entry.body` vs. `entry.more`; fixes #269 
This adds two parameters to `entry.body`/`.more`, `footnotes_defer` and `footnotes_link`, which indicates whether footnote rendering should be deferred for later, and where a footnote's link reference should point to.
In `entry.body` it defaults to `footnotes_defer=True` and the link pointing to the URL of the entry.
In `entry.more` it defaults to `footnotes_defer=False`, and the link is empty if we're not in an absolute context, or will be the absolute link of the entry if we are in an absolute context.
This also makes the link reference and definition IDs unique on a per-entry basis, so they won't interfere with each other on an index page or the like.
This will behave weirdly if `entry.body` and `entry.more` are …

Improve footnote references

---

publ/html_entry.py
tests/content/images/attribute renditions.md

Interpret `$attributes` as image renditions (removing the `$`). Fixes #312 
If an attribute name starts with `$`, treats it the same as `href` and also strips off the `$`. In this way we can support image renditions in custom JS libraries in `data-`attributes.
Also this fixes a subtle bug where `<img>` tags without a `src` attribute will crash, useful for supporting e.g. ondemand-loaded images.
See `tests/content/images/attribute renditions.md`

Interpret image renditions in $-annotated attributes

---

publ/__init__.py
publ/config.py
publ/tokens.py

Gets rid of an old/confusing configuration mechanism; fixes #302 
It turns out `config.secret_key` was only being used in one place anymore. Good thing, too!
Configuring it in the configuration dict now generates a warning, which will become an error in the future.

Remove config.secret_key, replace with app.secret_key

---

publ/entry.py
publ/html_entry.py
publ/markdown.py
publ/path_alias.py
tests/content/markdown_ext/_.cat
tests/templates/plaintext.html
tests/templates/sitemap.html

Make all markdown and HTML body processing accept `markup=False`
Moved the HTML stripper into `html_entry` where it belongs, and made it part of the `html_entry.process` pipeline, when `markup=False`. Now it applies to anywhere that handles Markdown or HTML.
Added a Markdowny description to the `markdown-ext` category, and added two templates, `sitemap` and `plaintext` to test it.

Universal support for markup=False

---

Pipfile.lock
publ/html_entry.py
publ/image/local.py
publ/markdown.py
publ/utils.py
tests/content/images/html renditions.html
tests/content/images/image renditions.md
tests/content/images/shaped images.md

Refactors `LocalImage.get_rendition`; fixes #173 
Rather than having separate pipelines for determining the filename and the rendering of the file, this gloms them together in a more extensible way that also doesn't require adding increasingly many arguments for every operation.
This also fixes a bug where different quantization levels for PNGs and GIFs wouldn't have rendered out separate images, and also improves the quality and file size for flattened images by pre-composing the background before crop-scaling.
This also adds the `scale_filter` image rendition argument, documented in https://github.com/PlaidWeb/publ-site/commit/54de24a861a1258713f18e50b99ce36401cb6d61
Added quantization tests, and verified all of the existing image tests still work correctly.

Refactor LocalImage rendering mechanism

---

publ/entry.py
publ/html_entry.py
publ/markdown.py
tests/content/toc/postprocessing.md
tests/content/toc/screwy.md
tests/content/toc/toc.md
tests/templates/_entry.html
tests/templates/toc/entry.html

Implement table of contents and heading anchors; fixes #56 
This adds `id` attributes to Markdown headings, and `entry.toc` that will render out the headings outline as an ordered list.
The following configuration options are added to entry content properties:
* `toc_link`: The base URL for table of contents links
* `heading_link_class`: The HTML `class` attribute to add to the self-link from headings in `entry.body`/`more`
* `heading_link_config`: Additional attributes to add to the self-link from headings (e.g. `title`, `data-*`)
* `heading_template`: A template for formatting headings in `entry.body`/`more`; can contain the following:
* `link`: a tag that links back to this heading
* `text`: the formatted text of the heading
Default is `{link}</a>{text}`
`entry` now also gets a …

Implement heading anchors and tables of content

---

publ/entry.py
publ/markdown.py
publ/utils.py
tests/content/toc/postprocessing.md
tests/content/toc/screwy.md
tests/templates/_entry.html
tests/templates/toc/entry.html

Reduces the number of redundant calls for ToC and footnote determination; fixes #334 
There are several performance optimizations that make constructs such as
```
{% if entry.toc %}
<h2>Table of Contents</h2>
{{entry.toc}}
{% endif %}
```
much faster. Some of the changes involved:
* `CallableProxy` now memoizes the default return (using common external variadics as cache keys; currently `flask.request.url` and `user.get_active` but adding more is easy)
* `entry` now keeps track of the various counters for markdown ToCs and footnotes on a per-section basis, so render functions don't have to do full content layout just to get the counters
* There is also now a dedicated ToC/footnote counter which is much faster than using the full Markdown renderer (and also doesn't result in spurious image …

Improve ToC and footnote performance

---

publ/config.py
publ/entry.py
publ/rendering.py
tests/content/duplicate id.md

Fix some edge conditions in how `Entry-ID` headers are updated; fixes #340 
* Improves the type annotations on `Entry.get`
* Fixes a few things that were impacted by that
* Improve the logic behind page redirection/reindexing of entries whose `Entry-ID` header changes outside of index generation
* Refactors `rendering.render_entry` to make it a bit less monolithic

Improve the way that entry IDs get reconciled

---

Pipfile.lock
publ/__init__.py
publ/category.py
publ/entry.py
publ/model.py
publ/path_alias.py
publ/rendering.py
pylintrc
tests.py
tests/content/aliases/_.cat
tests/content/aliases/alias template.md
tests/content/aliases/aliases and mounts.md
tests/content/aliases/canonical.md
tests/content/aliases/redirections.md
tests/content/auth/auth canonical.md
tests/content/auth/auth redirect.md
tests/templates/archive.html

Adds `Path-Mount` and `Path-Canonical` to entry metadata; closes #209 
Adds two new entry metadata fields:
`Path-Mount`: Like `Path-Alias`, but the standard entry URL will not redirect; the original canonical URL remains.
`Path-Canonical`: Like `Path-Mount`, except the standard entry URL will redirect to this entry.
In both of the above, specifying a template will treat the template as an *entry* template, rather than a category template; in `Path-Alias`, the optional template parameter still remains as a category view redirection.
This also adds `Path-Mount` to category views, which behaves identically to the entry version (except templates are of course used as a category template).
See tests in `/aliases/`.

Alternate Path-Alias mechanisms

---

publ/__init__.py
publ/entry.py
publ/html_entry.py
publ/markdown.py
publ/utils.py
tests/content/toc/postprocessing.md
tests/templates/index.txt
tests/test_html_entry.py
tests/test_utils.py

Have HTML renditions with `markup=False` remove `<del>` and `<s>` tags by default; provide finer-grained `strip_html` Jinja filter as well.
Strikethrough text is, by its nature, not intended to be parsed as the final readable text. Having an entry titled, for example, "This is why I'm ~~sad~~ happy," will look like "This is why I'm sad happy" in non-markup contexts. So, this makes the default markup-stripping rules remove `<del>` and `<s>` elements entirely, rather than simply removing their tags, thus rendering `This is why I'm ~~sad~~ happy` as "This is why I'm happy."
For finer-grained control, the `html_entry.strip_html` function has also been provided as a global Jinja2 filter, so that template authors can get better control of this mechanism, or so that they can, for example, …

Improved HTML stripping functionality

---

Makefile
Pipfile.lock
publ/model.py
publ/rendering.py
tests/content/status/illegal.md
tests/content/status/teapot.md

Adds the `ILLEGAL` (with synonyms `DMCA`, `BURNED`, and `BURNT`) and `TEAPOT` status types to entries. Fixes #361

Add support for a few more entry status dispositions

---

publ/__init__.py
publ/rendering.py

Make logout function work again; fixes #372 
One of the changes to cache-busting meant that a db_session was required for `render_publ_template`, but the logout view controller didn't have a db_session, since why would it? This just wraps the entire `render_publ_template` in its own db_session (which is a no-op if there already is one), and also puts the cachebuster computation inside another one to improve contention around some potential race condition cases.
While I was at it I also changed the session destruction to use `flask.session.pop` instead of setting a new empty string.

Make logging out work again

---

publ/rendering.py
publ/view.py

Filter `view.deleted` correctly on count-based pagination views
On a count-based pagination, `view.deleted` was using the count to restrict the number of entries to fetch, rather than restricting it based on the items that are visible on the page. This changes `view.deleted` to restrict deleted entries to the ones which came before the next page.
Manually tested with beesbuzz.biz content. As with most things this would benefit greatly from actual unit tests.

Improve view.deleted on count-based paginations

---

publ/__init__.py
publ/config.py
publ/entry.py
publ/index.py
publ/maintenance.py
publ/model.py
publ/rendering.py

Rewrite the indexer scheduling logic to prevent a bunch of problems; hopefully fixes #370 
Now when it detects files changing, it will queue the changes up for a second (by default) before it starts processing them, and the processing will go in batches based on what additional changes occur during the previous batch.
Additionally, there is a safeguard where if the file fingerprint on a source file changes while the scan-and-fixup process happens, it will abort the write.
If a file disappears before the index gets updated (for example, when the process is shut down), the associated entry record will be marked GONE instead of being deleted from the database. This prevents the renderer from dying due to access to a deleted record.
This is still a piecemeal solution and #371 will still be …

Rewrite the indexer scheduling logic

---

Pipfile.lock
publ/category.py
publ/entry.py
publ/index.py
publ/links.py
publ/model.py
publ/queries.py
publ/view.py
tests/content/attach/another.md
tests/content/attach/main.md
tests/content/attach/supplement 1.md
tests/content/attach/supplement 2.md
tests/templates/_entry.html
tests/templates/attach/entry.html
tests/templates/attach/index.html
tests/templates/index.html
tests/test_html_entry.py

Allows attaching entries to other entries; fixes #355 
Adds a new header to entries, `Attach`, which associates another entry as an attachment to this one.
Adds some entry methods, `attachments` and `attached`, which list the attachments of this entry, and other entries this entry is attached to, respectively. These also take standard view parameters.
Adds four view parameters:
* `has_attachments`: boolean, restricts to entries with attachments
* `is_attached`: boolean, restricts to entries which have been attached
* `attachments`: entry, restricts to entries which are attachments of the specified one
* `attached`: entry, restricts to entries which the specified one is attached to
Tests in the `attach/` directory

Add the ability to attach entries to other entries

---

publ/entry.py
publ/model.py
publ/rendering.py
tests/content/entry_id/collision 1.md
tests/content/entry_id/collision 2.md
tests/content/entry_id/collision 3.md
tests/content/entry_id/renumber.md

Better-handle reindexing when an entry ID changes; fixes #381 
1. Restores the uniqueness constraint to `model.Entry.file_path`
2. When indexing a file, removes other database rows which reference the file path but with a different entry ID
3. Forwards requests for an updated entry ID based on the updated ID and not the (stale) database record
Created multiple new entries with the same ID; verified that they resolve the collision appropriately.
Created entry, indexed it, paused the indexer, changed the ID in the file, reloaded index page
Paused the indexer, changed the ID in the file, reloaded entry page with old ID
Paused the indexer, changed the ID in the file, loaded entry page with new ID
Paused the indexer, renamed a file, reloaded index page
Paused the indexer, renamed a file, …

Fix the logic for reindexing around ID changes

---

publ/__init__.py
publ/rendering.py
publ/tokens.py

Caches the authorization header output as part of the top-level template render. Fixes #386 
Moves render-side stashing into `flask.g.stash`, and makes the stash output part of what gets cached. This was easier in the long run than adding more and more things to cache, and safer than just caching all the things.
```sh
TEST_CACHING=simple ./runTests.sh fast
curl -H 'Authorization: Bearer '$(FLASK_APP=tests/app.py pipenv run flask publ token test:friend2) http://localhost:5000/auth/
```

Cache the WWW-Authenticate response

---

Makefile
publ/category.py
publ/entry.py
publ/index.py
publ/links.py
publ/rendering.py
publ/tokens.py
publ/user.py
publ/utils.py
publ/view.py

Improve the way we stash things on `flask.g`, and add object pooling for Entry, View, and Category. Fixes #387 
Now Entry, View, and Category objects get pooled for the life of the transaction. On particularly egregious views this speeds up performance around 15%!
Probably breaks external content-management scripts that are doing things they shouldn't be doing anyway (proper stable public API? what's that?)

Rework flask.g stashing to add proper object pooling

---

publ/__init__.py
publ/category.py
publ/cli.py
publ/config.py
publ/entry.py
publ/image/__init__.py
publ/image/local.py
publ/index.py
publ/links.py
publ/markdown.py
publ/model.py
publ/rendering.py
publ/template.py
publ/tokens.py
publ/user.py
publ/utils.py
tests/__init__.py
tests/test_config.py
tests/test_markdown.py
tests/test_utils.py

Removes the module global config; fixes #113 
Now the configuration is stored on an object that's owned by the Publ app, instead of being stashed in hinky, fragile module globals.
Also this finally starts to build a `PublMock` class for doing further unit test cases.
Instead of doing `from . import config` you do `from .config import config`.
test coverage 100%, manual smoke tests continue to work

Get rid of global config

---

publ/category.py
publ/entry.py
publ/markdown.py
publ/utils.py
tests/content/fenced code.md
tests/templates/style.css

Makes it possible to number lines in code blocks via CSS, and also provide permalinks to each line.
Code blocks are now line-enumerable, and provide per-line permalinks. These are all to be enabled via CSS. Code blocks that do not declare a language do not get the enumeration; to enumerate a text block, declare a language of `text`.
There is also additional Markdown extension; if the first line of a code block starts with `!`, that line will be used as a title caption for the code block.
This required refactoring item counters, which now count independently of any underlying buffers, which makes
it easier to reconcile IDs between each other. This helps to simplify the way we track items such as TOC headings, footnotes, and code blocks.
This changes the structure of fenced code blocks' …

Add enumerable code blocks and refactor the way counters work

---

publ/entry.py
publ/image/__init__.py
publ/image/image.py
publ/markdown.py
publ/utils.py
tests/content/fenced code.md
tests/content/images/figure.md
tests/content/images/image renditions.md
tests/static/fancy-code.css
tests/templates/style.css

Puts block code inside `<figure>` and cleans up the semantic HTML; fixes #399 
Allows putting image sets inside `<figure>`; fixes #400 
Also various cleanups and refactoring around some of the code touched by these things
The HTML structure of the fenced code blocks was a bit half-baked and a little too ad-hoc for my tastes. Rather than using yet another pile of poorly-specified unsemantic `<div>`s it seemed better to use semantic `<figure>`/`<figcaption>` elements. Switching to that also highlighted some of the issues with how image sets are handled, and the lack of ability to actually customize code block behavior at any level, so this adds a few configuration settings for fenced code as well as the ability to specify settings at the code block level, and also refactors argument parsing …

Improve block code and image set semantics

---

publ/entry.py
publ/tokens.py
tests/content/attach/auth.md
tests/content/attach/main.md
tests/templates/attach/entry.html

`Entry.attachments` only returns attachments that the user is authorized to see. Fixes #379 
Also changed `tokens.request()` to return `None`, since there's no reason to actually return the user that's passed in and doing this allows its use inside a list filter.
Added authorization test to the `attach/` tests.

Add authorization check to entry attachments

---

poetry.lock
publ/__init__.py
publ/default_template/_admin.html
publ/model.py
publ/rendering.py
publ/user.py
tests/templates/index.html
tests/templates/userinfo.html

Fixes #407 
`user` now has the following additional fields:
* `profile`: the Authl user profile (currently only available if the user logged in via Authl and not e.g. a bearer token)
* `last_login` and `last_seen`: the dates when the user last logged in and was last active, respectively
* `identity`: The identity URL
* `humanize`: A humanized version of the identity URL
`user.name` now is a human-readable user name, equivalent to `user.profile.name` if that exists, or `user.humanize` if not.
`user.profile` is only valid if the user logged in against the current database; this has implications in load-balanced configurations, or after Publ upgrades or database resets.
`user.name` is no longer a valid hyperlink.

Add support for Authl profiles

---

publ/rendering.py
tests/content/aliases/exceptions.md
tests/templates/index.html

fixes #240 
see tests in `/alias/exceptions.md`

Allow path-alias to override exceptions

---

poetry.lock
publ/__init__.py
publ/cli.py
publ/config.py
publ/rendering.py
publ/tokens.py
publ/user.py
pyproject.toml
tests/__init__.py
tests/templates/index.html
tests/templates/userinfo.html
tests/test_tokens.py

Allows templates to provide a user-visible bearer token; fixes #411 
Reworks how tokens are generated and validated.
Because AutoAuth is dead in the water and the token_endpoint only existed for AutoAuth, all that stuff is removed. The auth upgrade hooks have also been simplified, and are only retained in case we decide to add something else with them, or if AutoAuth comes back someday.
The `{{token_endpoint}}` template function no longer exists, not that it was ever useful.
Added unit tests for generating and parsing tokens
Added `curl` sample to `/userinfo` page on test site, and verified it works.

Add user.token template function, and remove deprecated AutoAuth stuff

---

poetry.lock
publ/rendering.py
publ/user.py

Allow changing user permissions to invalidate caching; fixes #390 
If there's a user, adds their permissions mask to the render cache key. Also, reduces the TTL on the cached permissions masks.
1. Ran tests with `TEST_CACHING=simple ./runTests.sh`
2. Logged in as user `test:newuser`, and loaded the `auth` tests page
3. Reloaded a few times to verify that the page render was cached. Added `test:newuser` to the friends group, reloaded again before TTL expired, still got old page, then after the TTL expired, reloaded again and got the new page.
4. Removed `test:newuser` from the friends group, and repeated step 3

Add user's permissions to the cache key

---

publ/queries.py
publ/rendering.py

Improves the way that errors get handled in certain malformed URL scenarios; a better fix for #416 
b98271c fixed some of the most egregious 500 ISEs but there were still plenty coming through from certain badly-behaving robots; for example, URLs like `/?date=2010070` and `/?id=asdf` were passing the view validator but still causing exceptions in the query generator.
Now the query generator catches those underlying exceptions and promotes them to `InvalidQueryError`, which in turn gets handled as a `400 Bad Request`.

Improve the error handling for certain malformed dates and entry IDs

---

publ/config.py
publ/html_entry.py
publ/image/external.py
publ/image/image.py
publ/markdown.py
test_app.py
tests/__init__.py
tests/content/images/html renditions.html
tests/test_html_entry.py

Adds the ability to globally configure the default layout settings for `entry.body`/`entry.more`/etc.
Closes #424 
The configuration object now takes an additional dict, `layout`, which provides defaults for layout methods. For example,
```
app = publ.Publ(name, {
'layout': {
'max_width': 768,
'max_height': 1024
}
})
```
Additionally, some fixes were made to how default attributes get applied to pure-HTML entries, and external images now use CSS to specify the container size instead of always applying max_width to the `width` attribute.
Added a global `max_width` default of 768 to the test app, and verified that all of the larger-than-768xwhatever images were clamped to 768xwhatever, and that it could be overridden on a per-image basis if needed.

Add global layout configuration

---

publ/category.py
publ/entry.py
publ/model.py
publ/queries.py
publ/utils.py
publ/view.py
tests/content/tags/tag1.md
tests/content/tags/tag2.md
tests/content/tags/tag3.md
tests/templates/tags/index.html

Hide `Hidden-Tag` from category tag browsing; closes #401 
There is now a proxy object `EntryTagged` which tracks the actual entry placement in tags, and tracks whether the tag was hidden or not, and all of the queries have been updated accordingly.
This also does some more normalization on how tags are handled on view specs and `category.archive`, so they are now always case-folded and frozenset-ordered in URLs.
See the tests in `tags`, including the `always-hidden` tag which is always hidden (and thus doesn't appear in the category browser at all).

Don't display hidden-tag tags in category.tags

---

Makefile
publ/entry.py
publ/model.py
publ/queries.py
publ/utils.py
tests/content/tags/multiple.md
tests/content/tags/normalization.md
tests/content/tags/normalized.md
tests/test_utils.py

Improve the way that tags are normalized and displayed.
Fixes #430. Fixes #431 
When tags are stored in the database, they use the slugified form of the tag name, instead of simply casefolding it. This way, tags such as `neko` and `ねこ` are treated equivalently, and punctuation is also folded away (e.g. `dance dance revolve` and `dance, dance, revolve` are also equivalent). This has the side effect of also making view URLs always 7-bit-clean, albeit in a reductively Anglicizing way.
When tags are displayed from `view.tags` (or anything else which is processed through `utils.TagSet`), it now consults the database for the display name of the tag. This uses the most recently-indexed denormalization of the tag.
This does *not* change the display of tags in `entry.tags` (by design).

Improve tag normalization

---

poetry.lock
publ/__init__.py
publ/config.py
publ/tokens.py
publ/user.py
pyproject.toml
tests/__init__.py
tests/templates/userinfo.html
tests/test_tokens.py
tests/users.cfg

Implements Ticket Auth, per #405 
This change adds support for [TicketAuth](https://indieweb.org/IndieAuth_Ticket_Auth) as well as the necessary parts of an IndieAuth token endpoint. The following flows are supported:
* Automatically sending a ticket if someone signs in from a provider that supports TicketAuth
* Manually requesting a ticket via `https://example.com/_tokens?me=URL_HERE`
* Verifying the ticket via the [token verification flow](https://indieauth.spec.indieweb.org/#access-token-verification) at `https://example.com/_tokens`
This also automatically adds the appropriate `Link` header to all server responses. Additionally, this re-enables the `token_endpoint` Jinja global for use in templates (for example, if someone wants to provide a "send me a ticket" form).
By default, …

Implement Ticket Auth

---

.vscode/settings.json
poetry.lock
publ/cards.py
publ/entry.py
publ/html_entry.py
pylintrc
tests/content/cards/markdown in the summary.md
tests/content/cards/strikethrough.md
tests/templates/cards/entry.txt
tests/test_html_entry.py

Properly strip HTML from the OpenGraph tag, and add full markdown support to provided summaries.
Fixes #449 
The flow control of summary text was a bit convoluted, and wasn't going through the same HTML processing as other things, all in the name of micro-optimizations. The new flow, while less optimized, makes the code a lot easier to follow, at least in principle. It could still stand to have some refactoring.
`entry.summary` now has feature-parity with `entry.title`, and in particular it enables markup by default, and will need to have it suppressed with `markup=False`.

Properly handle markdown and HTML stripping in summary text

---

publ/entry.py
publ/html_entry.py
publ/markdown.py
publ/queries.py
tests/content/cards/image before first paragraph.md
tests/test_html_entry.py

* First-paragraph extraction now skips things like inline images in their own paragraph, and cleans up better
* Summaries no longer ever generate images on Markdown entries
I *really* want to refactor a bunch of this stuff now

Improve first-paragraph extraction

---

publ/image/__init__.py
publ/image/local.py
tests/__init__.py
tests/test_image.py

Delete empty image cache directories; fixes #458
Just as the image cache cleanup was never tested and wasn't working, same for the mechanism that actually deletes empty directories. It is now tested and verified working.

Delete empty cache dirs

---

publ/config.py
publ/tokens.py
publ/user.py
tests/test_tokens.py

Adds the `action=ticket` verb to the token endpoint, as discussed at https://github.com/indieweb/indieauth/issues/87
Awaiting confirmation of real-world functionality from @omz13.

Implement the provisional TicketAuth request flow

---

publ/config.py
publ/flask_wrapper.py
test_app.py

Allow disabling the index watchdog; fixes #475 
In production setups, dynamically creating content based on external events (form submissions, RSS feeds, etc.) is perilous because the index watchdog can end up stomping over the automated changes, which can lead to duplicate entries or other weird behavior. This adds a configuration option, `index_enable_watchdog`, which defaults to `True` but can be disabled, so as to allow a production site to choose when content gets reindexed.
Manually smoke-tested.

Allow disabling the watchdog for production use

---

publ/html_entry.py
publ/markdown.py
tests/content/cards/table in summary paragraph.md

Remove tables from entry summaries; fixes #478
Table content no longer appears as part of the "first paragraph" in HTML summaries, and the `<table>` element gets removed from the plaintext summary.
`tests/cards/table in summary paragraph.md`

Properly strip tables when extracting an entry summary

---

publ/default_template/_admin.html
publ/model.py
publ/tokens.py
tests/test_tokens.py

When a user obtains a token via TicketAuth, add them to the known user table; fixes #483 
When a user signs in via the TicketAuth request flow, also retrieve their IndieAuth profile; fixes #484 
This adds a `last_token` column to the user table, and updates that when a user obtains a token grant. it also takes advantage of the fact the IndieAuth profile is being fetched as part of parsing out the endpoint, and uses that to update the user's profile.
There is a schema change, so a site reindex will take place.

Register users who log in via TicketAuth grant

---

publ/tokens.py
publ/user.py
publ/utils.py
tests/test_tokens.py
tests/test_utils.py

…uth requests
Canonicizes identity URLs to make the netloc case-insensitive and path non-empty.
Supports `rel="canonical"` on TicketAuth grant requests. Fixes #486 
The users `http://example.com`, `http://Example.com`, and `http://example.com/` should all be equivalent.
Also, since TicketAuth has no mechanism for the endpoint to provide its own canonical identity, the only way for TicketAuth to prove ownership of a canonical URL is for the profile to provide `rel="canonical"` and for the ticket granter to forward its request to that canonical URL. So this change will forward a TicketAuth grant request if `rel="canonical"` is provided, with no trust given to the forwarding page (to avoid the situation where for example `https://alice.example` provides a TicketAuth endpoint and also a …

Canonicize user identity URLs

---

publ/entry.py
publ/user.py
tests/__init__.py
tests/test_entry.py

Enforce attribute security on `.get` and `.get_all`
Now when doing `.get` on a protected attribute, it will return blank unless the new argument `always_allow=True`.
Finally added some heckin' unit tests for `publ.entry`

Enforce security on Entry.get, Entry.get_all

---

publ/flask_wrapper.py
publ/image/__init__.py
publ/image/local.py
tests/content/images/image renditions.md

Only render an image when it's first requested  by a browser. Fixes #455 
Instead of immediately scheduling images for rendering at page-render time, this shoves the render request into an unwieldy, grotesquely-long URL that encodes the render request state, and then the `_async` image handler is responsible for generating the render request from that.
This uses signed URLs to avoid situations where someone may construct a malicious render request externally. The downside is that in a load-balanced scenario, this requires that all backing instances use the same `app.secret_key` or that the load balancer provides strong connection affinity, but that's currently the case for all user authentication as well.
There should be no impact on users, aside from some edge cases where images will …

Defer the rendering of images to the first actual request

---

publ/entry.py
publ/image/local.py
test_app.py

On systems with a 32-bit `time_t`, `OverflowError` occurs when trying to set a date beyond the 32-bit rollover. This fixes #394 
If soemone's still running Publ on a 32-bit system in 2038 they have bigger problems.
Unit tests pass, this is difficult to properly test on 64-bit systems though (and I don't have any 32-bit systems available to test on).

Handle date-related exceptions on entry parsing more broadly

---

publ/queries.py
publ/view.py
tests/templates/queries.html
tests/templates/test_invalid_filter_arg.html

`view()` now only accepts filter parameters, rather than silently ignoring link parameters which should be given to `view().link` instead.
Fixes #506 
There was an issue with how view-as-call-site accidentally made it too easy to pass in a silently-ignored parameter such as doing `<a href="{{view.previous(template='foo')}}>` instead of the (correct) `<a href="{{view.previous.link(template='foo')}}>`. This change ensures that only valid filter parameters get passed into the filter query.
This also finally refactored some fairly hairy, un-Pythonic code to be more Pythonic, so that's a nice bonus.
Templates will no longer silently fail if a link parameter is being passed into a filter context. Any errors caused by this were actually errors before, they were just not visibly so.
Ran all of …

Restrict view(...) arguments to valid query filters

---

publ/view.py
tests/templates/pagination.html

Followup fix for bug introduced in the fix for #506; date-based pagination was still passing view-specific parameters into the query, causing a failure if a sort order was specified (as well as the edge case of passing in `count` which is overridden by `date` anyway but is still allowed)

Fix date-based pagination when sort order is specified

---

publ/config.py
publ/flask_wrapper.py
test_app.py

Remove the dependence on the now-deprecated `Flask.before_first_request` functionality; fixes #500 
Flask 2.3 removed `before_first_request`, which Publ used as a hook for two purposes:
1. Configuring Authl
2. Deferring the content indexer until the first request, when running in debug mode
Purpose 2 was a workaround to a bug in Flask's hot-reload functionality that has been since fixed, and purpose 1 was something I went back and forth a few times on how the `secret_key` should be configured in the first place; originally I wanted it to be an up-front config value but that led to some inconsistencies with Flask's API.
Anyway, the removal of `before_first_request` forced the issue and since there's now a security vulnerability against Flask 2.2, an upgrade to 2.3 was required, so this …

Remove before_first_request dependency

---

publ/entry.py
publ/flask_wrapper.py
publ/html_entry.py
publ/markdown.py
publ/search.py
tests/content/cards/list in summary.md
tests/templates/first-paragraph.html
tests/test_html_entry.py

Fixes the way that we extract the first paragraph, and exposes a filter to the Jinja templating engine.
Fixes #497 
Rewrote the `html_entry.FirstParagraph` thing to correctly filter out all non-inline content, and also added `markup` and `strip_tag` parameters to the `html_entry.first_paragraph` function. This also exposes said function as a Jinja template filter, with optional parameters of `markup=True` (keep internal markup) and `strip_tag=False` (remove outermost `<p>` tag(s)).
This now strips non-paragraph text from entry summaries, including headings, list items, and so on.
Added unit test to `test_html_entry.py` and ad-hoc test suite in the `/first-paragraph` template.

Improve first paragraph filter and expose as a Jinja filter

---

publ/entry.py
tests/content/bodybool/_.cat
tests/content/bodybool/big empty body more.md
tests/content/bodybool/body only.md
tests/content/bodybool/body separator.md
tests/content/bodybool/fully empty.md
tests/content/bodybool/more only.md
tests/content/bodybool/separator whitespace.md
tests/content/bodybool/whitespace.md
tests/templates/bodybool/index.html

Make whitespace-only entry parts not count as truthy
On my site, sometimes files with a lot of whitespace sneak in, and end up causing the wrong layout rules to trigger (for example, with reaction posts). This change ensures that sections which are just whitespace appear as empty instead.
If someone's actually relying on whitespace appearing as a valid empty section, they'll need to put in an `&nbsp;` or similar.
See test suite in `/bodybool`

Ignore entry parts which are just whitespace

---

publ/entry.py
publ/rendering.py
publ/user.py
test_app.py

Set a cache-control header based on whether the page makes use of user identity; fixes #525 
If a page doesn't make use of entry authentication, or doesn't request stuff from the current userinfo, set a cache-control header that allows caching.
If the page does use entry authentication or does request stuff from userinfo, disallow caching.
There is a slight gap in that there's no way to tell if userinfo was requested if there is no logged-in user. However, in manual smoke tests, Firefox seems to discard cache entries once the user logs in, likely because of `Vary:Cookie` behavior, so this is probably a non-issue (and to that end it might actually be safe to always set cache-control with `private, max-age=NNN`).
max-age will be set based on the server-side caching configuration, with a …

Enable cache-control for requests that aren't user-dependent

---

publ/flask_wrapper.py
tests/content/auth/userinfo-embed.md

Fixes #524 
Sets the same-site cookie policy to `Lax` and also disables access to the session cookie via JavaScript, providing better clickjack mitigation.

Set same-site cookie policy

---

poetry.lock
publ/image/image.py
tests/content/images/gallery_id and link.md

Add `link=True` as an option to image renditions, to explicitly self-link to the fullsize rendition while overriding the lightbox gallery. Fixes #538 
See tests in `images/gallery_id and link.md`

Allow images to self-link while overriding the lightbox

---

publ/rendering.py
tests/content/emptycat/subcat/entry.md

Properly redirect on a category with no content but with subcategory content when given a non-`/`-terminated URL. Fixes #545 
When checking to see if a URL is a malformed category URL, also accept it if there are matching subcategories. For example, `http://example.com/emptycat` redirects to `https://example.com/emptycat/` if there are valid entries within the `/emptycat/subcat` category.
See the simple `/emptycat` test.

Properly redirect malformed empty category URLs

---

poetry.lock
publ/entry.py
publ/flask_wrapper.py
publ/image/local.py
publ/rendering.py
publ/view.py
pyproject.toml

Update dependencies and then fix some linting and typing issues that came from changes
`email.message`'s `get_payload()` is now variadic; for now we just assume it's a `str` although this will probably break in the future.
`PIL.Image`'s typing situation has gotten stricter as of 10.3.0, so this forces version 10.3 as a minimum and also fixes it to use the correct object typename. 10.3 also finally promoted `_getexif` to a public API.

Update dependencies and delint

---

publ/category.py
publ/entry.py
publ/flask_wrapper.py
publ/template.py
tests/templates/entry-retrieval.html

Adds a `get_entry(id)` template function, and context-relative functions for doing entry-relative image retrieval
`get_entry` is a new function that allows retrieving a specific entry by entry ID, if available to the current user.
The `Entry`, `Category`, and `Template` classes now have an `image` method which allows retrieving an image from their respective contexts. This is useful for doing relative image resolution.
The template `entry-retrieval.html` retrieves two hardcoded entry IDs, and also attempts to resolve an image from both of them.

Add direct entry retrieval and relative image fetching

---

publ/entry.py
publ/model.py

Just parse the entry ACL rules from a string instead of trying to be too fancy in the database
Profiling my website found that a *large* amount of the template render time was spent in the pagination, and that in turn was spending a *large* amount of time processing the permission ACL, which in turn required a lot of overly-complicated database access. There is no reason for this to be in the database when it's faster to just parse the ACL string directly instead of having to do a lot of marshaling, indexing, and so on.
Bumps the schema, so sites will have to reindex.
Thoroughly tested using the `auth/` test suite.

Replace overwrought database ACL test with simple string parsing

---

publ/entry.py
publ/view.py

Remove some full-table scans for authorization checks
It turns out that Pony's "lazy loading" of query results will immediately realize the entire query into a list at the drop of a hat, and you really need to use LIMIT and OFFSET to prevent that from happening.
Because of how authorization filtering works in Publ, count-based paginations were not using LIMIT and OFFSET. Now they are, and this has sped up rendering the global Atom feed on beesbuzz.biz by a significant factor.
Many huge thanks to @BearPerson / @AlsoBearPerson for helping me to figure out what was going on here, and being way more tenacious about digging through Pony than I am.
Ensured that the paging and auth/paging test suites still behave correctly.

Speed up auth filtering by many orders of magnitude

---

publ/rendering.py
publ/template.py
tests/content/accept header.md
tests/templates/accepts.atom
tests/templates/accepts.htm
tests/templates/accepts.html
tests/templates/accepts.txt
tests/templates/accepts.xml

Properly support HTTP `Accept:` and remove the ad-hoc template priority
Fixes #157 
Instead of the ad-hoc MIME type and template mapping by extension nonsense, this change makes it so that the HTTP `Accept:` header drives the template selection logic. If a template is directly selected by full filename it'll still be used (and this will also override `Accept:` but if only a partial filename is given then it'll find the best match based on MIME types as determined by Python's [`mimetypes`](https://docs.python.org/3/library/mimetypes.html) library.
This makes it in particular such that you can provide feeds in different formats with e.g. `feed.rss` and `feed.atom` and `feed.html` and then depending on what the client is looking for, it'll map `feed` to the best-fitting one.
It also supports …

Properly support HTTP Accept: and remove the ad-hoc template priority

---

publ/entry.py
publ/index.py
publ/model.py
publ/queries.py
tests/content/attach/main.md
tests/content/attach/status-attachment.md

If an entry has a status of ATTACHMENT (or ATTACH) it will only be visible from an attachment context (e.g. `entry.attachments`), and will never appear in a view.
Fixes #548 
See `tests/attach/main.md` and `tests/attach/status-attachment.md`

Add status:ATTACHMENT

---

publ/flask_wrapper.py
publ/image/__init__.py
publ/image/local.py
tests/content/images/image renditions.md
tests/test_image.py

Removes the image rendering threadpool, switches to blocking image rendering.
Fixes #591
The background rendering threadpool made sense in the early days of Publ when I was still trying to figure out how things should work, and when images were immediately rendered by the template itself. In the long run that has turned out not to be terribly helpful, and can actually cause massive performance and reliability issues in a lot of deployment scenarios.

Remove the async image renderer

---

publ/entry.py
tests/content/attach/fix-582/fix-1.md
tests/content/attach/fix-582/fix-10.md
tests/content/attach/fix-582/fix-2.md
tests/content/attach/fix-582/fix-3.md
tests/content/attach/fix-582/fix-4.md
tests/content/attach/fix-582/fix-5.md
tests/content/attach/fix-582/fix-6.md
tests/content/attach/fix-582/fix-7.md
tests/content/attach/fix-582/fix-8.md
tests/content/attach/fix-582/fix-9.md
tests/content/attach/fix-582/root.md

Corrects an issue with first-index of new content with attachments; fixes #582 
In the event that a new entry and its attachments were being imported and assigned IDs, oftentimes the indexer would miss the attachment relationship. This turned out to be a simple issue where the initial fixup pass (which assigned the entry ID) was overriding the next indexer pass (that would have added the attachment relationship to the database).
Generated a bunch of empty entries and their attachments all at once, in `content/attach/fix-582`. The attachment relationship was established by the end of the first index cycle.

Fix the fixup mechanism with unknown attachments

---

publ/rendering.py
tests/templates/unauthorized.html

Don't attempt to render the `unauthorized` entry template on the admin dashboard; fixes #594 
The `rendering.handle_unauthorized` flow only makes sense in an entry context, which the admin dashboard is not.
1. Test accessing `/_admin` as not-a-user, and log in as not-an-admin
2. Test it again logging in as an admin

Fix 403 error handling for the admin dashboard
