PlaidWeb/Publ

Pipfile
Pipfile.lock
publ/__init__.py
publ/caching.py
setup.py

Configures the cache after the configuration is loaded; Fixes bug #61 
The cache object was being erroneously configured at import time rather than at application setup time. Now it configures the cache after setup.
Made changes to publ.beesbuzz.biz site files and reloaded before the cache expiration.

Fix caching configuration

---

publ/entry.py

Fixes #70 
Instead of using `str(message)` to encode the message and its headers in one swell foop, it encodes them separately in an encoding-preserving manner.
Round-tripped a bunch of UTF-8 headers

Prevent email.message from MIME-encoding headers

---

publ/category.py
publ/entry.py
publ/index.py
publ/model.py
publ/path_alias.py
publ/queries.py
publ/rendering.py
publ/utils.py
publ/view.py

Fixes #44 and adds the ability to add metadata to categories, and improves the default name generation as well

Add category meta

---

publ/async.py

Fixes #85  in the most trivial way imaginable

Bust the async handler cache

---

publ/category.py

Add a breadcrumb trail for navigation; fixes #92 
Sample usage:
```
<h2>Navigation</h2>
<ul class="breadcrumb">
{% for cat in category.breadcrumb[:-1] %}
<li><a href="{{cat.link}}">{{cat.name}}</a></li>
{% endfor %}
<li class="here">{{category.name}}</li>
</ul>
```

Add breadcrumb trail

---

publ/rendering.py

Allows categories and entries to override their index and entry templates.
Categories get a new property, `Index-Template`, which indicates which alternate template they can use for rendering their index, without overriding their subcategories' index.
Categories and entries get a new property, `Entry-Template`, which indicates which alternate template they should use for rendering entries, without overriding subcategories' entries.
This also adds the concept of a "private template," where if a template name starts with `_` it is inaccessible to the public router and can only be used by internal functions (this will be useful for #90).
Tested with usual smoke test suites on publ.beesbuzz.biz

Add the ability to override Index-Template and Entry-Template

---

publ/entry.py
publ/path_alias.py
publ/utils.py
publ/view.py

Fixes #107 by adding the necessary stuff for a `week` pagination view.
Default span formats in `view.range` have changed to use `/` instead of `-` separators.

Support weekly pagination

---

publ/image.py

Resolves #121 
Images now have an optional markdown attribute, `shape`, which can either have:
* `True` -- use the base rendition of the image
* a URL -- use the specified URL for the shape
When a shaped image is floated, text wraps around it based on its alpha channel.
This also adds a couple of other attributes, `style` and `img_class`, which add stuff to the `style` and `class` entry, respectively. (This is in addition to the `div_class` which adds a class to the containing div.)

Add support for shapes and arbitrary styles

---

publ/image.py

only apply the size-related aspects to the shape stuff

---

publ/cards.py
publ/entry.py
publ/image.py
publ/markdown.py
publ/utils.py

Adds the ability to dynamically generate "more images" text blocks in an image set; fixes #110

110 gallery morelink

---

publ/entry.py
publ/model.py
publ/view.py

Fixes #149 
It does the thing
Added sort-title to the publ site manual section

Add sort-title field

---

publ/queries.py
publ/rendering.py

When attempting to paginate against a nonexistent entry, raise a more appropriate error; fixes #217 
For now an invalid query raises its own error class, which gets converted to a 404 by the rendering functions.
Used issue reproduction case

Raise more appropriate error for invalid pagination

---

Makefile
Pipfile
Pipfile.lock
publ/__init__.py
publ/caching.py
publ/config.py
publ/path_alias.py
setup.py
tests.py

Fixes #205 and generally improves PyDoc docs.

refactoring and cleanups

---

publ/html_entry.py
tests/content/plain.html
tests/templates/_plain.html

fixes #242 
nobody cares but I figured...

Implement handle_decl

---

publ/__init__.py
publ/default_template/_admin.html
publ/default_template/error.html
publ/entry.py
publ/model.py
publ/rendering.py
publ/template.py
publ/user.py
publ/utils.py
setup.py
tests/users.cfg

* Implements an authentication dashboard; fixes #232 
* Improves management of built-in templates; fixes #245 
There is now an authentication dashboard. It's fairly basic but it handles my needs.
As part of improving the login flow, the `unauthorized.html` template is no longer guaranteed to get an `entry` or `category` object.

Implement authentication dashboard

---

publ/image/external.py

Fixes default alt text on external images; closes #288 
I am dumb
External image tests were broken; now they're fixed.

Fix broken _get_url invocation

---

publ/__init__.py
publ/config.py
publ/tokens.py

Implement IndieAuth token endpoint; closes #296 
Implements the IndieAuth bearer token part of the AutoAuth (and MicroPub) flow
Used https://gimme-a-token.5eb.nl/ to check codes against both https://beesbuzz.biz/ and https://commentpara.de/

Implement token endpoint

---

Makefile
Pipfile
Pipfile.lock
publ/cards.py
publ/category.py
publ/config.py
publ/entry.py
publ/image/__init__.py
publ/image/external.py
publ/image/image.py
publ/image/local.py
publ/links.py
publ/maintenance.py
publ/model.py
publ/path_alias.py
publ/queries.py
publ/rendering.py
publ/template.py
publ/tokens.py
publ/user.py
publ/utils.py
publ/view.py
setup.py
tests.py
tests/content/duplicate id.md
tests/content/images/favicons.md
tests/content/images/image renditions.md

Adds type annotations throughout the codebase; fixes #252 
This adds mypy to the build process, and also adds annotations to pretty much everything where it makes sense.
Specific things which are omitted: 
* return values for functions that return polymorphically to Flask
* any attempt at being strict with kwargs
* a few Pony-specific things that don't play nice with its dynamic binding model
As part of doing this, no major typing inconsistencies were found, but a few things were cleaned up and which will hopefully avoid mistakes in the future.
Also, `CallableProxy` no longer accepts a `None` argument; instead, use `CallableValue(fixed_value)` .
Standard battery of tests; also improved the image rendition parsing tests since I was cleaning up that code

Add type annotations

---

Pipfile.lock
publ/entry.py
publ/markdown.py
tests/content/footnotes/smartypants.md

Applies the full HTML post-processing pipeline to entry footnotes. Fixes #331 
Lets Markdown footnotes include smartquotes as well as HTML `src`/`href` rewrites.
See test `footnotes/smartypants.md`

Apply HTML post-processing to footnotes

---

Makefile
publ/entry.py
publ/image/local.py
publ/utils.py
tests/test_utils.py

Add unit tests and coverage; fixes #18 
There are finally some automated tests. They only scratch the surface of testing the system as a whole but they are a start.
This is the test plan.

Add unit testing and coverage

---

publ/view.py

Allow previous/next page from empty date-based views; fixes #35 
The pagination algorithm was implemented in a somewhat too-generically way that was both inefficient and incorrect. Now count-based pagination uses the neighbor-based stuff and date-based pagination just looks at the first entry after the current date range and the last entry before the current date range. Much more efficient.
Manually tested with the `date-based` tests, and with setting dates far in the future or to empty months or whatever. Also verified that count-based pagination still works.

Allow date-based pagination from empty views

---

publ/__init__.py
publ/cli.py
publ/entry.py
publ/index.py
publ/model.py
publ/rendering.py
publ/tokens.py
publ/utils.py
tests/templates/index.html

Add some CLI commands and fix other related issues along the way
fixes #319
fixes #304 (in theory)
There are now two `flask` CLI commands, `flask publ reindex` and `flask publ token`, which can be used for various site automation purposes.
This also fixes a few miscellaneous bugs discovered while poking around, or which were convenient enough to fix while doing these things anyway.

CLI command additions

---

publ/rendering.py
tests/templates/index.html

fixes #240 
see tests in `/alias/exceptions.md`

Allow path-alias to override exceptions

---

poetry.lock
publ/model.py
tests/content/collisions/_1.cat
tests/content/collisions/_2.cat

Fixes #421 
Added a unique constraint to `model.Category.category` and some vague tests to validate this.

Add an appropriate index to Category

---

.gitignore
poetry.lock
publ/__init__.py
publ/config.py
publ/entry.py
publ/markdown.py
publ/search.py
publ/view.py
pyproject.toml
test_app.py
tests/templates/index.html
tests/templates/search.html

Adds full-text search; fixes #146 
This adds a new template API, `search`, which allows doing a full-text search on entries. It needs to be enabled in the local configuration via the `search_index` configuration value.
The API is a bit incomplete at present; in particular, pagination could be a lot better.

Full-text search

---

poetry.lock
publ/__version__.py
pyproject.toml

Release v0.7.14

---

publ/__version__.py
pyproject.toml

Release to let folks update watchdog

Release v0.7.23

---

publ/__version__.py
pyproject.toml

Release v0.7.26

---

publ/category.py
publ/rendering.py
tests/templates/category-index/_alt.html
tests/templates/category-index/alt.html
tests/templates/category-index/index.html
tests/templates/index.html

Just some code quality fixes from things I noticed post v0.7.26.

Cleanups to the index template selection code and tests thereof

---

publ/entry.py
tests/templates/tags/index.html

Coalesce entry.archive() template-name
